export { default as Article } from "./sections/Article";
export { default as Hero } from "./sections/Hero";
export { default as OurProcess } from "./sections/OurProcess";
export { default as Partner } from "./sections/Partner";
export { default as Services } from "./sections/Services";
export { default as Button } from "./ui/Button";
export { default as Content } from "./ui/Content";
export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
